### ISSUE TITLE
deploy jstat-gui

### ISSUE THREAD

**Issue by jethronap** [jethronap/jstat-gui#16]
research on how and where to deploy the app. netlify - heroku

**Comment by jethronap** [comment]
we can follow the instructions provided from [this](https://medium.com/@ryanyuliu/deploy-your-spring-boot-project-properly-for-free-66ae38012698) article or [this](https://www.callicoder.com/deploy-host-spring-boot-apps-on-heroku/) one following methods one or three. and see how it goes.

**Comment by pockerman** [comment]
great...raise your sleeves then :) :)

**Comment by jethronap** [comment]
https://jstatgui.herokuapp.com
