### ISSUE TITLE
Add DescriptiveStatisticComputeController

### ISSUE THREAD

**Issue by pockerman** [jethronap/jstat-gui#24]
The ```DescriptiveStatisticsComputeController``` is responsible for two things:

- GET: Serves the page to the client that allows to set a descriptive statistics computation
The user should:
1. Specify the data set for which the computation is requested
2. Specify the column or "All" for which the computation is to launched
3. The columns of the data set  should come from the backend
- POST: Accepts the filled user form and creates the task(s) for the computation

It redirects to a page where the computation completion can be queried. Thus we should be able to distinguish between computing tasks. e.g. use some sort of name mangling

**Consider:** We could write to a DB when a calculation is started and finished a poller can then query this and once the computation is finished serve the results somehow

**Consider:** The user should be able to save in the DB the computed model for future use under a name

**Comment by pockerman** [comment]
How are we going with this issue?? Is it done?

**Comment by jethronap** [comment]
not yet. in a couple of days.
